language: go

go:
  - "1.10"

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/cover

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go vet goject.go
  - $HOME/gopath/bin/golint goject.go
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...
